Repository Ashlar/cryptometa, pull requests merged in 2021-06, with the labels that each got.

#100 Add Flat
  data/zilliqa/assets/zil133vrh59edllqz7guq7htfthjmj7gct5jxqqtl7/logo.png
  data/zilliqa/assets/zil133vrh59edllqz7guq7htfthjmj7gct5jxqqtl7/meta.json
Labels: invalid, pending

#105 Add Corgi Token
  data/zilliqa/assets/zil1x5qv9rsqznkd8fyhc2e9jxwkxztlnhhlkzm0ee/logo.png
  data/zilliqa/assets/zil1x5qv9rsqznkd8fyhc2e9jxwkxztlnhhlkzm0ee/meta.json
Labels: pending

#106 Update Logo mistake in logo.png upload
  data/zilliqa/assets/zil1x5qv9rsqznkd8fyhc2e9jxwkxztlnhhlkzm0ee/logo.png
Labels: pending

#109 Add HODL Token
  data/zilliqa/assets/zil177u3jh5x4hqual22zy7s2ru3gc2y4yq5wnq2un/logo.png
  data/zilliqa/assets/zil177u3jh5x4hqual22zy7s2ru3gc2y4yq5wnq2un/meta.json
Labels: pending

#107 MESSI token
  data/zilliqa/assets/zil1qzwxvp3wz3q5ewzg3afesut9pqfax0sjdyna42/logo.png
  data/zilliqa/assets/zil1qzwxvp3wz3q5ewzg3afesut9pqfax0sjdyna42/meta.json
Labels: pending

#111 Add MAMBO Token
  data/zilliqa/assets/zil1ykcdhtgyercmv7ndfxt00wm9xzpq4k7hjmfm4e/logo.svg
  data/zilliqa/assets/zil1ykcdhtgyercmv7ndfxt00wm9xzpq4k7hjmfm4e/meta.json
Labels: pending

#116 Add Reward Token
  data/zilliqa/assets/zil1dccsly0lwkkxhxxazldcnph05v2dz8maz46g05/logo.png
  data/zilliqa/assets/zil1dccsly0lwkkxhxxazldcnph05v2dz8maz46g05/meta.json
Labels: pending

#114 Add Alvin Token
  data/zilliqa/assets/zil1r0yhrkzawstrk3n29xkpnw6mw634cs52x9366l/logo.png
  data/zilliqa/assets/zil1r0yhrkzawstrk3n29xkpnw6mw634cs52x9366l/meta.json
Labels: pending

#123 Tesla Token
  data/zilliqa/assets/zil1r32n9p5u5k99u5nl5tjvndyy0mjpcdvswzmu7w/logo.svg
  data/zilliqa/assets/zil1r32n9p5u5k99u5nl5tjvndyy0mjpcdvswzmu7w/meta.json
Labels: pending

#118 Add ZiLBOX Token
  data/zilliqa/assets/zil1s68pllqj8n5tw4exvayqafhw0l03rp546l3mzw/logo.png
  data/zilliqa/assets/zil1s68pllqj8n5tw4exvayqafhw0l03rp546l3mzw/meta.json
Labels: pending

#132 WOJAK Token
  data/zilliqa/assets/zil1p5a30n55ek790f99zh8l27s0l8f0axrjes07sq/logo.png
  data/zilliqa/assets/zil1p5a30n55ek790f99zh8l27s0l8f0axrjes07sq/meta.json
Labels: pending

#148 DELTA
  data/zilliqa/assets/zil1n744td8d2knf5gu84j23842qeaeynyqy8dcvh3/logo.png
  data/zilliqa/assets/zil1n744td8d2knf5gu84j23842qeaeynyqy8dcvh3/meta.json
Labels: pending

#145 add token zia
  data/solana/assets/78kKxYt1c8exXFRhc8gZ2uUySeEBM3DyMhxcf61UmkvZ/logo.png
  data/solana/assets/78kKxYt1c8exXFRhc8gZ2uUySeEBM3DyMhxcf61UmkvZ/meta.json
Labels: pending

#151 Update Diana token logo to svg
  data/zilliqa/assets/zil13f36stxyqxrethgrfqmlcr87rgm2chvv8rv86k/logo.png
  data/zilliqa/assets/zil13f36stxyqxrethgrfqmlcr87rgm2chvv8rv86k/logo.svg
  data/zilliqa/assets/zil13f36stxyqxrethgrfqmlcr87rgm2chvv8rv86k/meta.json
Labels: pending

#164 [zilliqa] Add Dragonworld (Dragon)
  data/zilliqa/assets/zil1xq3g89vzdnjkt585v45h6uz44amw7d865weh7g/logo.png
  data/zilliqa/assets/zil1xq3g89vzdnjkt585v45h6uz44amw7d865weh7g/meta.json
Labels: pending

#157 [zilliqa] Add Zia (ZIA)
  data/zilliqa/assets/zil1srct7xr7slactkrqcsu7rr4lc7x8x0e52tq7p7/logo.png
  data/zilliqa/assets/zil1srct7xr7slactkrqcsu7rr4lc7x8x0e52tq7p7/meta.json
Labels: lazy, pending

#165 [zilliqa] Add Planetarize (PLANET)
  data/zilliqa/assets/zil1nhuzjg452rkdzrfh7swllr4eq2g8t0lfgu2z38/logo.png
  data/zilliqa/assets/zil1nhuzjg452rkdzrfh7swllr4eq2g8t0lfgu2z38/meta.json
Labels: pending
