Repository Ashlar/cryptometa, pull requests merged in 2021-08, with the labels that each got.

#201 Update HODL Token Logo
  data/zilliqa/assets/zil177u3jh5x4hqual22zy7s2ru3gc2y4yq5wnq2un/logo.png
Labels: pending, lazy

#203 Add YODA Token
  data/zilliqa/assets/zil1vdc79fg75sth96xnt6xmq5f55swcd5t6m5zhvn/logo.png
  data/zilliqa/assets/zil1vdc79fg75sth96xnt6xmq5f55swcd5t6m5zhvn/meta.json
Labels: lazy

#205 [zilliqa] Add Eggzilla (EGGZ)
  data/zilliqa/assets/zil12rpq9shyvrd2rzrcyx2jn5t74y9g5c2xn095qe/logo.png
  data/zilliqa/assets/zil12rpq9shyvrd2rzrcyx2jn5t74y9g5c2xn095qe/meta.json
Labels: pending

#207 [Zilliqa] Update BLOX (BLOX)
  data/zilliqa/assets/zil1gf5vxndx44q6fn025fwdaajnrmgvngdzel0jzp/logo.png
Labels: pending

#206 [zilliqa] Add Alex A. Valdez (AAV)
  data/zilliqa/assets/zil15wctna0k3zn0jgfemlns9zj23sue34a003sf3e/logo.png
  data/zilliqa/assets/zil15wctna0k3zn0jgfemlns9zj23sue34a003sf3e/meta.json
Labels: pending

#211 [zilliqa] Add Consult (CONSULT)
  data/zilliqa/assets/zil108ex3na3dvwnjq5p4nls4z3gjy8fx66693hf4d/logo.png
  data/zilliqa/assets/zil108ex3na3dvwnjq5p4nls4z3gjy8fx66693hf4d/meta.json
Labels: pending

#215 [Zilliqa] Add Library Skynetwork (BOOK)
  data/zilliqa/assets/zil1jy9cy2j5xzzzq2v6lpkpuk22u7atf7ud3kt2tm/logo.png
  data/zilliqa/assets/zil1jy9cy2j5xzzzq2v6lpkpuk22u7atf7ud3kt2tm/meta.json
Labels: pending
