Repository Ashlar/cryptometa, pull requests merged in 2021-11, with the labels that each got.

#295 [zilliqa] Add Oasis Of Amazing Creatures (OAC)
  data/zilliqa/assets/zil1gcdkmkuunj0l6hjl48zzye50g397dgslzdf4uk/logo.png
  data/zilliqa/assets/zil1gcdkmkuunj0l6hjl48zzye50g397dgslzdf4uk/meta.json
Labels: lazy

#302 [Zilliqa] Update Markhors & More (MNM)
  data/zilliqa/assets/zil1dpj3xj7mryncq6fyqrcdlgx5txlnnhafpq382l/logo.svg
Labels: pending

#300 [Zilliqa] Add DopeCrewFriends NFT (DCF)
  data/zilliqa/assets/zil1nfuy0fuvdun80m6f5vxfqycz0caphpf8tksmlt/logo.png
  data/zilliqa/assets/zil1nfuy0fuvdun80m6f5vxfqycz0caphpf8tksmlt/meta.json
Labels: lazy

#298 [zilliqa] Add Dr.Death's Redemption (The Tighe-Mearns-Smith Original Comic Book Series)
  data/zilliqa/assets/zil1r72ndmu2rt244ktdgamusy8ne6h9ef3tggahd0/Logo.png
  data/zilliqa/assets/zil1r72ndmu2rt244ktdgamusy8ne6h9ef3tggahd0/meta.json
Labels: lazy

#309 [Zilliqa] Add EnviZion (EVZ)
  data/zilliqa/assets/zil1hzt4wchy6yu9pufk07gzptsj8m3spztuqmeucs/logo.png
  data/zilliqa/assets/zil1hzt4wchy6yu9pufk07gzptsj8m3spztuqmeucs/meta.json
Labels: pending

#318 [Zilliqa] ADD Fkn Apes Club (FAC3)
  data/zilliqa/assets/zil1ay6tggqqcjntdn65jpe7cqfjc2ndq46gsvukk3/logo.png
  data/zilliqa/assets/zil1ay6tggqqcjntdn65jpe7cqfjc2ndq46gsvukk3/meta.json
Labels: pending, lazy

#317 [Zilliqa] ADD SOULFUL SAINTS (SOULS)
  data/zilliqa/assets/zil1dm584qxhqqu46rgn50cj74yp47x7w3gf7q4j36/logo.png
  data/zilliqa/assets/zil1dm584qxhqqu46rgn50cj74yp47x7w3gf7q4j36/meta.json
Labels: pending

#332 [Zilliqa] ADD The Dirty Mind (DIRTY)
  data/zilliqa/assets/zil1sle9slj8mdzt9ma0gccn7f7artsvsx2eva966m/logo.png
  data/zilliqa/assets/zil1sle9slj8mdzt9ma0gccn7f7artsvsx2eva966m/meta.json
Labels: pending

#334 [Zilliqa] Add The Perfect NFT (TPN)
  data/zilliqa/assets/zil1gy2qe326evmfyvjmu2dctv0hzj78dxhzejns8w/meta.json
  data/zilliqa/assets/zil1qwkgpyvdzg4yg4gh878w65k8eqm2c0r0j3qnrx/logo.png
  data/zilliqa/assets/zil1qwkgpyvdzg4yg4gh878w65k8eqm2c0r0j3qnrx/meta.json
Labels: pending

#329 [Zilliqa] Add XIDR (XIDR)
  data/zilliqa/assets/zil1cuf78e3p37utekgk0gtcvd3hvkrqcgt06lrnty/logo.png
  data/zilliqa/assets/zil1cuf78e3p37utekgk0gtcvd3hvkrqcgt06lrnty/meta.json
Labels: pending

#335 [Zilliqa] ADD The Zilkrows (ZLK)
  data/zilliqa/assets/zil14hw3vgte5szr30c30qde7j4dctp4a606x2qvew/logo.png
  data/zilliqa/assets/zil14hw3vgte5szr30c30qde7j4dctp4a606x2qvew/meta.json
Labels: pending

#336 [Zilliqa] Update Gary (GARY)
  data/zilliqa/assets/zil1w5hwupgc9rxyuyd742g2c9annwahugrx80fw9h/logo.svg
Labels: pending, lazy

#355 [Zilliqa] ADD Earthworm Jimmy (worm)
  data/zilliqa/assets/zil10zxwml0gh7qvskaytw2psy86k7qkh33l0hmx3q/logo.png
  data/zilliqa/assets/zil10zxwml0gh7qvskaytw2psy86k7qkh33l0hmx3q/meta.json
Labels: pending

#348 [Zilliqa] ADD SPARDAHALLOWEEN (SPAHA)
  data/zilliqa/assets/zil1zjavpru0u7sztrhphz3pjm7rc8r6u4ss5q7449/logo.png
  data/zilliqa/assets/zil1zjavpru0u7sztrhphz3pjm7rc8r6u4ss5q7449/meta.json
Labels: pending

#353 [Zilliqa] ADD Daetama (DTM)
  data/zilliqa/assets/zil1r85y05xqpdcudl7ktnt9k0nrm9r8l4pf25c28y/logo.png
  data/zilliqa/assets/zil1r85y05xqpdcudl7ktnt9k0nrm9r8l4pf25c28y/meta.json
Labels: pending
